== Два определения человека

[.lead]
Обсуждаем скрытую суть человека и секрет его процветания

Самое главное – правильно начать. Если при решении математической задачи в начале допускается ошибка, то все остальные вычисления, даже если они верны – являются ложными и пустой тратой времени. Поэтому мы начнем с главного - с антропологического определения: кто такой человек?

С биологической точки зрения человек – существо, похожее на обезьяну, но обладающее более сложными нервными функциями, обеспечивающими иной уровень мышления. Из этой антропологической предпосылки возникла общеизвестная гипотеза Дарвина о происхождении человека, которая до сих пор *не получила фактических доказательств* (и не получит их, в силу отсутствия в природе промежуточных эволюционных звеньев от обезьяны к человеку).

Однако данная предпосылка (родства человека с обезьяной) уже пронизывает собой всю жизнь современного общества: культуру, образование, политику, взаимоотношения между людьми. Потребности биологического человека те же, что и у животных: еда, сон, секс и оборона. То, что животное строит для сна и размножения примитивное жилье, а человек – из бетона и стекла, или что оно обороняется и нападает с помощью когтей и клыков, а человек – посредством ножа или даже с помощью атомной бомбы – не делает человека чем-то по *Смыслу* иным: это та же обезьяна, только, можно сказать, более рафинированная и «масштабная».

В то же время всегда существовала совсем иная антропологическая предпосылка, которая определяет человека как существо принципиально отличное от всего остального животного мира. *Человек – это тот, кто способен постигать Смыслы Творения, и потому может жертвовать биологическим человеком в себе, точнее превосходить его. Эта способность заложена в нас потому, что мы связаны не с животным миром, а с иным, высшим.* *_В данном определении биологический человек не отвергается, но ставится на службу Человеку духовному и становится его воплощением._*

В рамках первой, материалистичной антропологической парадигмы, культура предлагает нам в качестве идеала (а именно культура отвечает за формирование идеалов) поведение чисто биологического индивида, у которого имеется сильное тело, вызывающее страх у представителей своего пола, и сексуальное влечение у представительниц противоположного. Умные и способные особи признаются лидерами в животном социуме, и мы видим также в человеческой культуре, что люди, способные, например, красиво изъясняться и влиять на других, или быстрее других соображать, получают значительные преимущества и положение.

В любом биологическом обществе (стае) присутствуют, конечно, взаимоотношения, наиболее тесными из которых является половой союз и его расширение – дети. Животные нежны к своим детенышам - так устроено природой. И их общественная жизнь предполагает также наличие языка общения, который выражает определенные потребности и эмоции. Присутствует и образование, поскольку детенышей обучают соответствовать культурному коду, принятому в данной стае.

Но чем отличается Человек от человека биологического? Например, если человек сделает что-то нехорошее другому, себе подобному, тот даст отпор, чтобы неповадно было, либо смирится с этим, как более слабый. Так работает биологический культурный код и таковы требования материалистичного общества. Но Человек спросит: «Почему ты так со мной поступил?», т.е. с его стороны будет не реакция, а обращение к *Смыслу действия, к Человеку в человеке*. Если человек готов быть Человеком, то он задумается, почувствует голос совести, сделает выводы и извинится. Если же он находится еще под полным контролем биологического культурного кода, то есть является материалистом, то тогда вопрос не возымеет действия. В этом случае нужны уже ответные меры на понятном «родственнику обезьяны» языке. Однако в любом случае, *настоящий Человек видит в другом потенциал именно Человека, и старается пробудить его*.

Все существа имеют потребность в социально - биологическом половом союзе, однако потенциальный Человек создает семью с целью стать в ней Человеком поистине и дать своим детям не одно, но *два рождения: биологическое и духовное. Обществу, в котором семьи не разделяют этой ценности – не суждено войти в будущее.*

Материя нашего тела и ума находится под влиянием среды и ее установок, но дух (сознание) человека потенциально независим от материи. Однако до тех пор, пока дух не пробужден, мы отождествляем себя с телом и умом и тоже находимся под влиянием среды, будучи не способными сами на нее влиять. *Общественная среда подавляет дух человека, но она же способна и пробуждать его. +++<u>Все взаимоотношения в обществе, вся социально-экономическая жизнь, должны быть выстроены с целью пробуждения в человеке Человека – таково, по сути дела, __основное положение__ данной Концепции </u>+++. О том, что это значит и какими средствами может достигаться эта цель, и пойдет речь далее.* Именно присутствие людей духовного склада и их деятельность является главным активом общества, залогом его безопасности и процветания *,* а не дутые показатели экономического роста, которые сами по себе не говорят ни о чем. Цивилизация, ориентирующаяся в своей самооценке и оценке действующих в ней субъектов на ****достижения**** (в разных областях, в первую очередь - в экономике), исчерпала себя. Необходимо начать последовательно закладывать в систему образования, в существующие общественные институты следующую цивилизационную формулу: ****пробуждение Человека порождает высокое качество отношений, из которых проистекает экологичное процветание .footnote:[Clarification about this statement.] общества во всех сферах**. Последнее утверждение является обратной формулировкой основного положения данной Концепции, которое дано выше. Позже мы поймем, что обе формулировки одинаково важны и имеют разный смысл.