== Знакомьтесь: индивидуалист Творения

[.lead]
Для биологического человека закрыто будущее, ему надо меняться.

Процветание, основанное на социально - биологическом коде, на зависти и соперничестве, – не может в принципе быть залогом безопасности и стабильности в обществе. *Здоровье общественного организма – это качество взаимоотношений между всеми его частями, что подобно обмену веществ в организме*. Темпы же роста экономики — это увеличение «массы тела», что не отражает состояния здоровья: такое увеличение обычно связано с ожирением из-за нарушения здорового обмена веществ, вызванного беспокойствами из-за собственной жадности или зависти. Что является действительным критерием оценки здоровья: увеличение массы тела или улучшение обмена веществ? Даже без медицинского образования каждый способен дать верный ответ. *Здоровое увеличение массы тела возможно лишь только при правильном обмене веществ.*

Есть и другой момент. Мы озвучиваем его потому, что если в Концепции присутствует недосказанность, не цельность, то она не будет эффективной. Биологический человек всегда игнорирует главный экзамен и факт его жизни – смерть. Этот факт имеет глубокий _Смысл,_ доступный только Человеку: *все, что мы делаем в этом мире, останется здесь, а с собой мы заберем только опыт своего духа*. Из этого следует, что если мы действительно заинтересованы _в духовно-гуманистическом обществе_ (определяющем человека не как потомка обезьяны, а иначе), то мы не должны использовать в качестве приоритетных критериев оценки его развития экономические показатели. Экономика конечно важна, но ровно настолько, насколько помогает человеку избавиться от синдрома борьбы за существование и сосредоточиться на Человеческом, на творчестве, на служении духа. Борьба за существование превращает человека в биоробота, препятствует раскрытию талантов и инициативы в отношениях - истинного источника счастья. *Цивилизация, нацеленная не на пробуждение духа человека, а на его эксплуатацию в материальных целях – не может быть связана со Всевышним, даже при наличии института религии*.

В материалистичном обществе во всех сферах жизни доминирует социально-биологический код, то есть на всех уровнях: на бытовом, политическом и даже на религиозно-организационном – присутствует *примат собственных групповых интересов и готовность их отстаивать за счет других*. *Диалог в обществе носит при этом формально-показной характер, т.к. все важные Смыслы (то есть Истина)*** отождествляются с собственными представлениями - предубеждениями**. Данная ситуация могла вполне сходить с рук в ранних исторических условиях, когда каждая страна или любая другая общность очерчивали свою территорию и жили лишь своими представлениями. Однако в новых условиях взаимопроникновения сфер влияния и потребностей данный мыслительный код начал представлять угрозу для всего человечества и каждой его части.

И угроза эта заключается не только в том, что здесь заложен механизм перманентного развития конфликтной энергии вширь и вглубь цивилизации, но и в том, что через непродуктивность социально - биологического кода в человеческом обществе происходит уполномочивание крайне влиятельной группы «архитекторов нового мира», которые предлагают «лечение хуже самой болезни», наподобие самоубийства – как способа ухода от страданий жизни. Их подход заключается в том, чтобы максимально *понизить порог основных человеческих само-отождествлений* : половых, групповых, национальных и религиозных, и активировать в человеке *индивидуалистичное «оно»* , являющееся потребителем материальных благ. Поскольку «оно» себя ни с чем не отождествляет, то можно будет создать *унифицированное технократическое общество* без серьезной конфликтности. 

Заметим, что в животном мире не выражено четко такое явление как «индивидуалист», - *такой склонностью снабжен именно человек, чтобы дать
ему _возможность_ отличать себя от стаи, и поступать по собственной
прихоти-разумению. Это своего рода особая «опция», предусмотренная
Творцом для пробуждения в человеке осознанного Человека, личности*. К
сожалению, человек использует, как правило, данную ему возможность не по
назначению, становясь *индивидуалистом Творения* , т.е. чем-то худшим
чем животное. У животного всегда есть отождествление себя с полом и
стаей. Поэтому когда самец добывает материальные блага (пищу), то
приносит их своим детенышам, самке и также всей стае. Животные, из-за
своего отождествления, будут, конечно, враждебно относиться к
представителям другой стаи (поскольку только *Человек* может жить так,
чтобы всем хватало), но они *никогда не будут индивидуалистами, живущими
по собственной прихоти, для себя. Некоторый дух любви и служения
присутствует уже в самой природе, как вложенное в нее Творцом указание
на возможность над-биологического существования*. *Биологическое
существование – это всегда общественная жизнь, всегда взаимоотношения,
однако над-биологическая жизнь – _это то же самое, но только когда
обмен эмоциями и исполнение социальных ролей имеют важные Смыслы, т.е.
исходят из духа_. Только тогда, когда мы переживаем нечто ** важное
****(не в плане наших интересов, а для нашего духа), только тогда наши
эмоции обретают энергию, чистоту и глубину, становясь**** любовью ****.
Поэтому в дальнейшем под взаимоотношениями мы в основном будем понимать
именно духовные взаимоотношения, действующим лицом и продуктом которых
является Человек**.