== Введение

В эпоху коммуникаций, когда Интернет, средства связи, масс-медиа и взаимозависимый рынок труда помещают в общее пространство людей разных вер, наций и культур, назрела необходимость сформулировать и согласовать общую ценностную платформу для цивилизации. Различные религии мира, культуры планеты на протяжении многих столетий формировались вдали друг от друга, когда не было больших возможностей для путешествий, контакта с другой культурой. Теперь, когда в командировку и в отпуск люди летают во все точки мира, когда представители разных обществ, культур и народов работают на одном предприятии и живут в одном доме, **возникла необходимость в универсальной цивилизационной концепции, которая бы отражала суть всех духовных учений мира, и находилась в гармонии с современной наукой**. Если такая Концепция не будет взята на вооружение, то в мире в целом, и каждом регионе в отдельности с каждым годом будет нарастать напряжение и отчуждение, у которого, в силу невозможности возвращения к замкнутости, будет только один выход – конфликт и разрушение.

Однако данная Концепция будет выполнять не только общечеловеческую
цивилизационную функцию, она будет работать на *объединение и
возрождение национальных общностей, которые, включаясь в процессы
глобальной стандартизации, объективно обрекают свою культурно -
историческую самобытность на вымирание*.

И наконец третья функция Концепции заключается в том, что она поможет
нам *соединить внешнего человека с внутренним Человеком* : в каждом из
нас живет потребность реализовать свою уникальность и сделать что-то
настоящее в жизни, но мы отворачиваемся от Человека в себе, оправдывая
это тем, что общество не заинтересовано в нашей духовной
само-актуализации и втягивает нас во внешний режим выживания и
конкуренции. Данная Концепция призвана помочь нашему внутреннему
Человеку обрести силу и так изменить наше окружение.

Эта Концепция основана на фундаментальных принципах мироустройства,
поэтому она интуитивно понятна (самоочевидна) и воодушевляет. Будучи
основой устойчивого развития личности и общества, она ясно передаёт суть
всех духовных учений и с научной объективностью объясняет необходимость
смены существующей цивилизационной парадигмы развития, которая *устарела
и не позволяет ответить на вызовы нового Времени*.
