= Summary

. link:introduction.adoc[Введение]

Актуальность данной Концепции для общества и читателя

. link:01.adoc[Два определения человека]

Обсуждаем скрытую суть человека и секрет его процветания

. link:02.adoc[Знакомьтесь: индивидуалист Творения]

Для биологического человека закрыто будущее, ему надо меняться

. link:02.adoc[«Архитектурный план материализма» или самоуправление?]

Устаревшая информационно-финансовая власть уступает место самоуправлению

. link:02.adoc[Главные определения: пять кодов влияния]

Излагаем объективную основу Концепции

. link:02.adoc[Что такое сверх-общественная идеология?]

Маски сброшены: определяемся в одной из двух идеологий

. link:02.adoc[Почему провалилась попытка жить по человечески?]

Наше недавнее прошлое с позиции знания о «кодах»

. link:02.adoc[Пять типов общественного устройства]

Изучаем разные способы организации жизни, их плюсы и минусы

. link:02.adoc[Ловушка «правового» общества]

Свернув «на право», повернули «налево»

. link:02.adoc[О собственности и экономике]

Правда ли что возможно процветание без совести?

. link:02.adoc[Родина – она для всех или только для «своих»?]

Откуда приходит Родина и куда затем уходит

1.  Возможно ли «помирить» веру со знанием?

Почему у человечества разделились два «полушария»: наука и религия

1.  О детях и образовании

Почему дети вдруг стали «обузой» и что с этим делать

1.  О сакральности полового союза

Мужчина и женщина – это материальные тела или нечто большее?

1.  «Фабрики грез»

Настоящие Аватары бывают не только в кино

1.  «Большие новости» о времени

Или эволюция от Человека к обезьяне

1.  Система управления высшего типа

Мудрость и управление творят чудеса

1.  Нечеловечная необходимость и Человеческие отношения

О том как необходимость разрушает мир и как любовь его спасает

1.  Духовно-нравственный кодекс – как основа коллегиального общества

Берем практические инструменты для претворения в жизнь Концепции